export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_CLEAR = 'CART_CLEAR';
export const CART_SET_FROM_DB = 'CART_SET_FROM_DB';
export const CART_LOADING = 'CART_LOADING';
export const CART_GET_FAIL = 'CART_GET_FAIL';